language: r
cache: packages
warnings_are_errors: false
dist: trusty
notifications:
    on_success: never
    on_failure: true
r_packages:
  - covr
r_github_packages:
  - r-lib/covr
after_success:
  - Rscript -e 'library(covr); codecov()'
  - Rscript -e 'covr::coveralls()'
